"""
Digest Formatter
Takes a list of processed agenda dicts and renders a clean
plain-text + HTML digest for email delivery.
"""

from datetime import datetime

CATEGORY_LABELS = {
    "SANDAG_DIRECT": "🎯 SANDAG Direct",
    "TRANSPORTATION_FUNDING": "💰 Transportation Funding",
    "HOUSING_RHNA": "🏘️ Housing / RHNA",
    "ACTIVE_TRANSPORTATION": "🚲 Active Transportation",
    "PORT_OF_ENTRY": "🌎 Port of Entry / Cross-Border",
}

CATEGORY_ORDER = [
    "SANDAG_DIRECT",
    "PORT_OF_ENTRY",
    "TRANSPORTATION_FUNDING",
    "HOUSING_RHNA",
    "ACTIVE_TRANSPORTATION",
]


def format_digest(agendas: list[dict], run_date: str = None) -> dict:
    """
    Takes processed agendas (with relevant_items) and returns:
      {
        "subject": str,
        "plain_text": str,
        "html": str,
        "total_flagged": int,
        "jurisdictions_with_hits": int,
      }
    """
    run_date = run_date or datetime.now().strftime("%B %d, %Y")

    # Collect all flagged items, grouped by category
    by_category = {cat: [] for cat in CATEGORY_ORDER}
    jurisdictions_with_hits = set()
    total_flagged = 0

    for agenda in agendas:
        if not agenda.get("has_relevant_items"):
            continue
        jname = agenda["jurisdiction"]
        mdate = agenda.get("meeting_date", "")
        session = agenda.get("session_type", "")
        label = f"{jname}{' — ' + session if session else ''} ({mdate})"
        jurisdictions_with_hits.add(jname)

        for item in agenda.get("relevant_items", []):
            cat = item.get("relevance_category", "SANDAG_DIRECT")
            if cat not in by_category:
                cat = "SANDAG_DIRECT"
            by_category[cat].append({**item, "_source": label, "_agenda_url": agenda.get("agenda_url", "")})
            total_flagged += 1

    # --- Plain text ---
    lines = [
        f"SANDAG REGIONAL AGENDA DIGEST",
        f"{run_date}",
        "=" * 60,
        f"Flagged items: {total_flagged} across {len(jurisdictions_with_hits)} jurisdictions",
        "",
    ]

    if total_flagged == 0:
        lines.append("No regionally relevant items found in this cycle's agendas.")
    else:
        for cat in CATEGORY_ORDER:
            items = by_category[cat]
            if not items:
                continue
            lines.append(f"\n{'─' * 50}")
            lines.append(f"{CATEGORY_LABELS.get(cat, cat).upper()}")
            lines.append(f"{'─' * 50}")
            for item in items:
                lines.append(f"\n📍 {item['_source']}")
                num = item.get("item_number")
                lines.append(f"   Item {num}: {item['title']}" if num else f"   {item['title']}")
                lines.append(f"   {item['summary']}")
                lines.append(f"   → {item['relevance_explanation']}")
                lines.append(f"   Agenda: {item['_agenda_url']}")

    lines += [
        "",
        "─" * 60,
        f"Generated by SANDAG Agenda Digest · {run_date}",
        "Jurisdictions scanned: " + str(len(agendas)),
        "Reply to unsubscribe.",
    ]

    plain_text = "\n".join(lines)

    # --- HTML ---
    html = _render_html(by_category, total_flagged, len(jurisdictions_with_hits), len(agendas), run_date)

    return {
        "subject": f"SANDAG Agenda Digest — {run_date} ({total_flagged} flagged items)",
        "plain_text": plain_text,
        "html": html,
        "total_flagged": total_flagged,
        "jurisdictions_with_hits": len(jurisdictions_with_hits),
    }


def _render_html(by_category, total_flagged, jcount, total_scanned, run_date) -> str:
    sections = ""

    if total_flagged == 0:
        sections = "<p style='color:#666;'>No regionally relevant items found in this cycle's agendas.</p>"
    else:
        for cat in CATEGORY_ORDER:
            items = by_category[cat]
            if not items:
                continue
            label = CATEGORY_LABELS.get(cat, cat)
            item_html = ""
            for item in items:
                num = item.get("item_number")
                item_label = f"Item {num}: {item['title']}" if num else item["title"]
                item_html += f"""
                <div style="margin-bottom:18px; padding:14px; background:#f9f9f7; border-left:3px solid #2c5282; border-radius:3px;">
                  <div style="font-size:11px; color:#888; margin-bottom:4px;">{item['_source']}</div>
                  <div style="font-weight:600; color:#1a1a2e; margin-bottom:6px;">{item_label}</div>
                  <div style="color:#333; margin-bottom:6px; line-height:1.5;">{item['summary']}</div>
                  <div style="font-size:12px; color:#555; font-style:italic;">{item['relevance_explanation']}</div>
                  <div style="margin-top:8px;">
                    <a href="{item['_agenda_url']}" style="font-size:11px; color:#2c5282;">View full agenda →</a>
                  </div>
                </div>"""
            sections += f"""
            <div style="margin-bottom:30px;">
              <h2 style="font-size:14px; font-weight:700; letter-spacing:0.08em; text-transform:uppercase;
                         color:#2c5282; border-bottom:1px solid #ddd; padding-bottom:8px; margin-bottom:14px;">
                {label}
              </h2>
              {item_html}
            </div>"""

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="font-family: Georgia, serif; max-width:640px; margin:0 auto; padding:32px 20px; color:#1a1a1a; background:#fff;">
  <div style="border-bottom:2px solid #2c5282; padding-bottom:16px; margin-bottom:24px;">
    <div style="font-size:11px; letter-spacing:0.15em; text-transform:uppercase; color:#888; margin-bottom:4px;">
      SANDAG Public Affairs
    </div>
    <h1 style="font-size:22px; margin:0 0 4px; font-weight:700;">Regional Agenda Digest</h1>
    <div style="font-size:13px; color:#555;">{run_date}</div>
  </div>

  <div style="background:#f0f4ff; border-radius:4px; padding:12px 16px; margin-bottom:28px;
              font-size:13px; color:#2c5282;">
    <strong>{total_flagged} flagged items</strong> across
    <strong>{jcount} jurisdictions</strong> ·
    {total_scanned} agendas scanned
  </div>

  {sections}

  <div style="border-top:1px solid #eee; margin-top:32px; padding-top:16px;
              font-size:11px; color:#999; line-height:1.6;">
    Generated by SANDAG Agenda Digest · {run_date}<br>
    This digest is for internal SANDAG use. Items are AI-identified and should be verified against source agendas.
  </div>
</body>
</html>"""
